### PR TITLE
Add `link-button` directive

### PR DESCRIPTION
**Pull request by chrisjsewell**
Create clickable buttons, referencing URLs or References

FYI @choldgraf and @jorisvandenbossche

### CODE REVIEW

**Comment by choldgraf** [comment]
nice - lookin' good 👍

**Comment by jorisvandenbossche** [comment]
Oh, cool! This can replace the "custom-button" we did in pandas as well ;) 

And the "stretched-link" to make the full panel clickable is really nice. I seem to remember that we wanted to do that for our panels at the home page (https://pandas.pydata.org/docs/dev/index.html), but didn't directly succeed at it ;)

**Comment by chrisjsewell** [comment]
Cheers @jorisvandenbossche! I've just been adding it to the AiiDA docs:

```rst
.. panels::
   :body: text-center

   **Getting Started**

   First time user or are looking for installation instructions? Start here!

   +++++++++++++++++++++++++++++++++++++++++++++

   .. link-button:: intro/get_started
      :type: ref
      :text: To the getting started guides
      :classes: btn-outline-primary btn-block stretched-link
```

image

The nice thing about putting the buttons in the footer is that they all align. Although, I'd probably like to get rid of the outline and darker background of the footer.

**Comment by chrisjsewell** [comment]
Note I'm also considering #20

**Pull request merged**
