### PR TITLE
Use 16px as the "base" size for rem conversions

### PR DESCRIPTION
**Pull request by pradyunsg**
The borrowed/adapted code does not set the dimensions correctly, since this extension does not directly control the value of 1rem, and does not override it to be 20px like mkdocs-material does.

https://github.com/squidfunk/mkdocs-material/blob/d7c28f93195352541e444ba5f54a377ca24002fa/src/assets/stylesheets/main/layout/_base.scss#L35-L61

This PR sets 1rem to 16px (the default) which should result in expected behavior on basically all the Sphinx themes. :)

---

One of the symptoms is the thinner-than-expected underline and overline on the tabbed content.

### CODE REVIEW

**Comment by chrisjsewell** [comment]
Cheeers, but you didn't install pre-commit did you 😉

**Comment by pradyunsg** [comment]
Well, I made the PR from the GitHub UI. 🙃 

I've made a comment in #32 regarding the use of pre-commit for compiling the SCSS. :)

**Comment by chrisjsewell** [comment]
> Well, I made the PR from the GitHub UI

Thats surely always an issue for pre-commit check though, your always likely to break a pre-commit from the GitHub UI. I would always discourage to make changes purely via the GitHub UI.

**Comment by pradyunsg** [comment]
> our always likely to break a pre-commit from the GitHub UI

Well, not once http://pre-commit.ci/ is alive and installed. :P

**Comment by chrisjsewell** [comment]
Ok ta, this makes the labels fairly big, I'll merge this for now, but actually will then look to just make the label size configurable (like the colors)

**Comment by pradyunsg** [comment]
> this makes the labels fairly big,

Oooo. Interesting! Looking at the font-size rule, that seems to be the expected behaviour?

https://github.com/pradyunsg/sphinx-panels/blob/599687222609096dcfcda5ec764b3c94b174fa90/sphinx_panels/scss/panels/_tabs.scss#L99

**Pull request merged**
