### PR TITLE
👌 IMPROVE: Move from CSS to SCSS

### PR DESCRIPTION
**Pull request by chrisjsewell**
The goals were:

1. Good common CSS practices: using (linted) SASS, compressing compiled CSS, using hashes in filenames (and ideally also using source maps)
2. Allowing for "interactive development", with live rebuilds, while editing "watched" source files' both content files (i.e. `.md`,`.rst`,etc) and style files (i.e. `.scss`)

sphinx-panels does not contain any JS, and so I have not directly considered that.

The changes were:

1. SCSS compiling is internal to the sphinx-build, using pyscss. As we noted in executablebooks/sphinx-book-theme#200, libsass is the more "complete" compiler **but** it is quite "heavy-weight" for a dependency, requiring C-extensions. There is currently an annoying `FutureWarning` with pyscss that appears in build stdout, but the fix has been merged and hopefully should be released soon. pyscss does also currently preclude the addition of source maps 😢 
2. The CSS filename contains the content hash, to invalidate caches (closing executablebooks/sphinx-book-theme#204)
3. The CSS is written into the build folder, rather than a folder in the package directory (as is currently done in sphinx-book-theme)
4. All documents are re-written on CSS changes, this supports...
5. A tox.ini is added that includes a live rebuild environment, using [sphinx-autobuild](https://github.com/executablebooks/sphinx-autobuild), that now properly works! (i.e. css is updated in the build folder) Given this works in tox, I see no need for nox (as currently used in sphinx-book-theme).
6. Adds an scss linter in the pre-commit

The other option considered was to pre-compile the scss to css with a pre-commit hook (to ensure the css is kept consistent).
This negates the requirement for a sass compiler install dependency.
But I was having a look at this in https://github.com/executablebooks/pre-commit-scss, and its not trivial (dealing with git) and would be more difficult to get working with `sphinx-autobuild`

A note on to other implementation re CSS, for future discussion:

1. Sphinx offers a [templating functionality](https://www.sphinx-doc.org/en/master/development/theming.html#static-templates), whereby `css_t` are first processed by jinja. This allows for configuration based CSS, e.g. used in [insipid-sphinx-theme](https://github.com/mgeier/insipid-sphinx-theme/blob/eb8a53940b220aeed48c0749769774a1113c1859/src/insipid_sphinx_theme/insipid/static/insipid.css_t#L3). It's an interesting use case, however I don't like that this then prohibits good CSS development practices like those used above. If desired, one could think about confining such configuration to a single SCSS fragment, which is written dynamically (to override a default) before compilation.

2. pydata-sphinx-theme uses webpack to pre-compile JS/CSS (see [its guide](https://pydata-sphinx-theme.readthedocs.io/en/latest/contributing.html#developing-the-theme-css-and-js)). This is a more mature standard, but the drawback is that it adds a larger development dependency overhead, and does not fit in well (at least currently) with sphinx-autobuild "live development" or allow for configurational CSS.
  Edit: there is a live rebuild feature using yarn through: [webpack.dev.js](https://github.com/pandas-dev/pydata-sphinx-theme/blob/master/webpack.dev.js), but yeh it just adds a lot of overhead for a purely python package 🤔

### CODE REVIEW

**Comment by chrisjsewell** [comment]
@choldgraf @pradyunsg @AakashGfude you might want to have a look at this, as it's a prelude to changing sphinx-book-theme in the same way:

1. SCSS compiling is internal to the sphinx-build, using pyscss. As we noted in executablebooks/sphinx-book-theme#200, libsass is the more "complete" compiler **but** it is quite "heavy-weight", requiring C-extensions. There is currently an annoying `FutureWarning` that appears in build stdout, but the fix has been merged and hopefully should be released soon. pyscss does also currently preclude the addition of source maps 😢 
2. The CSS filename contains the content hash, to invalidate caches
3. All documents are re-written on CSS changes, this supports...
4. A tox.ini is added that includes a live rebuild environment, using sphinx-autobuild, that now properly works! Given this works in tox, I see no need for nox.

The other option considered was to pre-compile the scss with a pre-commit hook. I was having a look at this in https://github.com/executablebooks/pre-commit-scss, but its not trivial and wouldn't really work with  sphinx-autobuild

**Comment by chrisjsewell** [comment]
Also my sass game has upped a few levels, looking through the bootstrap repo 🤓

**Comment by pradyunsg** [comment]
My suggestion would be to forfeit keeping master installable via git, omitting the generated file from the repo and only adding the "original" sources here.

That's also what I'm doing in pradyunsg.me/furo.

**Comment by chrisjsewell** [comment]
> My suggestion would be to forfeit keeping master installable via git, omitting the generated file from the repo and only adding the "original" sources here.

I'm not sure what you mean by this? None of the generated CSS is part of the repo, only the source SCSS

**Comment by AakashGfude** [comment]
@chrisjsewell nice work. The hash encoding is also looking neat.

**Comment by pradyunsg** [comment]
> I'm not sure what you mean by this? None of the generated CSS is part of the repo, only the source SCSS

Ah, I meant:

- source repository
  - no generated CSS
  - source SCSS files
- distributions
  - generated CSS
  - no source SCSS files

Basically, there'd be a compile step between the source repository and the final distributions that get published on PyPI. I've opted for a Gulp-based pipeline over on the project I linked to (which lets me use popular/canonical implementations of the tools, instead of depending on ports).

**Comment by chrisjsewell** [comment]
Ok, I'm going to merge this, to record the changes. But I might play around with pre-packaging with webpack, gulp, parcel, etc

**Pull request merged**
